
localhost:
	jupyter-notebook --port=5900 --ip=150.217.37.50

presentation-make:
	jupyter-nbconvert oeis-tools.ipynb \
        --to slides \
        --stdout \
        --reveal-prefix http://cdn.bootcss.com/reveal.js/3.1.0 > talk.html


